# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:49:10+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetcountrystandardGetResponse(BaseModel):
    Code: Optional[str] = None
    CountryStandard: Optional[str] = None
    Credits: Optional[str] = None
